//综合服务
$(".news_moving").click(function(){
	$(this).css('background-image','url(images/news_moving_active.png)').css('background-repeat','no-repeat').css('background-size','cover');
});
$(".news_main").click(function(){
	$(this).css('background-image','url(images/news_main_active.png)').css('background-repeat','no-repeat').css('background-size','cover');
});
$(".news_curr").click(function(){
	$(this).css('background-image','url(images/news_curr_active.png)').css('background-repeat','no-repeat').css('background-size','cover');
});